export const imageUrls = {
  sunny: require("assets/icon-animation/sunny.json"),
  banner1: require("assets/image/banner1.jpg"),
  banner2: require("assets/image/banner2.jpg"),
  banner3: require("assets/image/banner3.jpg"),
  banner4: require("assets/image/banner4.jpg"),
  banner5: require("assets/image/banner5.jpg"),
  iconBag: require("assets/icon/bag.png"),
  iconNotification: require("assets/icon/notification.png"),
  iconFlashSale: require("assets/icon/sale.png"),
  iconNiceShop: require("assets/icon/nice.png"),
  iconPoints: require("assets/icon/point.png"),
  iconRice: require("assets/icon/rice.png"),
  iconNoodles: require("assets/icon/noodles.png"),
  iconVegetable: require("assets/icon/vegetable.png"),
  iconBBQ: require("assets/icon/bbq.png"),
  iconOther: require("assets/icon/other.png"),
  //
  iconHome: require("assets/icon/home.png"),
  iconHomeActive: require("assets/icon/home-active.png"),
  iconHeart: require("assets/icon/heart.png"),
  iconHeartBorder: require("assets/icon/heart-border.png"),
  iconHeartActive: require("assets/icon/heart-active.png"),
  iconOrder: require("assets/icon/order.png"),
  iconOrderActive: require("assets/icon/order-active.png"),
  iconGift: require("assets/icon/gift.png"),
  iconGiftActive: require("assets/icon/gift-active.png"),

  iconStar: require("assets/icon/star.png"),
  iconImage: require("assets/icon/image.png"),
  iconImage2: require("assets/icon/image2.png"),
  iconImage3: require("assets/icon/image3.png"),
};
